app_halaman_utama/urls.py
from django.conf.urls import url
from .views import index
from django.views.generic.base import RedirectView

urlpatterns = [
    url(r'^$', index, name='index'),
]

app_menanggapi/urls.py
from django.conf.urls import url
from .views import index, tambah_tanggapan

urlpatterns = [
	url(r'^$', index, name='index'),
	url(r'^tambah_tanggapan', tambah_tanggapan, name='tambah_tanggapan'),
    ]

app_profile/urls.py
from django.conf.urls import url
from .views import index

urlpatterns = [
    url(r'^$', index, name='index'),
]

forum_lowongan/urls.py
from django.conf.urls import url
from .views import *
#url for app
urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^add/$', add, name='add'),
    url(r'^delete/(?P<id>\d)/$', delete_forum, name='delete_forum'),
]

ppw_tp2/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic.base import RedirectView
import app_halaman_utama.urls as app_halaman_utama
import app_profile.urls as profile
import forum_lowongan.urls as forum
import app_menanggapi.urls as menanggapi

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^company/profile/', include(profile, namespace='profile')),
    url(r'^company/forum/', include(forum, namespace='forum_lowongan')),
    url(r'^company/menanggapi/', include(menanggapi, namespace='menanggapi')),
    url(r'^halaman_utama/', include(app_halaman_utama,namespace='app_halaman_utama')),
    url(r'^$', RedirectView.as_view(url='halaman_utama/', permanent=True), name='index')

]

app_halaman_utama/models.py
from django.db import models

# Create your models here.

app_menanggapi/models.py
from django.db import models
from django.forms import ModelForm
from forum_lowongan.models import Forum

class Comment(models.Model):
	content = models.TextField()
	created_on = models.DateTimeField(auto_now_add=True)
	forum = models.ForeignKey(Forum)

class CommentForm(ModelForm):
    class Meta:
        model = Comment
        exclude = ['created_on','forum']

app_profile/models.py
from django.db import models

# Create your models here.

forum_lowongan/models.py
from django.db import models
# from fitur1 import Company

# Create your models here.
class Forum(models.Model):
    date = models.DateTimeField(auto_now_add=True)
    content = models.TextField(max_length=500)
    company_id = models.IntegerField(default=0)

    class Meta:
       ordering = ['id']

forum_lowongan/forms.py
from django import forms

class ForumForm(forms.Form):
    content_attrs = {
        'class': 'form-control',
        'placeholder':'Deskripsi forum lowongan pekerjaan'
    }

    content = forms.CharField(max_length=500, widget=forms.TextInput(attrs=content_attrs))

app_halaman_utama/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
# Create your views here.
response = {}
def index(request):
    response['author'] = "Kelompok 8"
    html = 'halaman_utama/halaman_utama.html'
    return render(request, html, response)

# def to_profile(request):
#     return HttpResponseRedirect(reverse('profile:index'))

app_menanggapi/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from .models import Comment,CommentForm
from forum_lowongan.models import Forum

response = {}

def index(request):
	response['CommentForm'] = CommentForm
	html = 'app_menanggapi/app_menanggapi.html'
	forum = Forum.objects.all()
	response['forum'] = forum
	return render(request, html, response)
    
def tambah_tanggapan(request):
	form = CommentForm(request.POST or None)
	if(request.method == 'POST' and form.is_valid()):
		response['comment'] = request.POST.get('comment')
		response['id'] = request.POST.get('data.id')
		obj = Forum.objects.get(pk=response['id'])
		comment = Comment(response['comment'])
		comment.save()
		return HttpResponseRedirect('/menanggapi/')

app_profile/views.py
from django.shortcuts import render


# Create your views here.
response = {}
def index(request):
	response['author'] = 'Fakhril'
	html = 'profile.html'
	return render(request, html, response)

forum_lowongan/views.py
from django.shortcuts import render, redirect
from .models import Forum
from .forms import ForumForm
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

# Create your views here.
response = {}
def index(request):
    forum_list = Forum.objects.all()
    paginator = Paginator(forum_list, 3)

    page = request.GET.get('page')
    try:
        forum = paginator.page(page)
    except:
        forum = paginator.page(1)

    response['forum'] = forum
    return render(request, 'forum.html', response)
def add(request):
    if request.method == 'POST':
        form = ForumForm(request.POST)
        response['form'] = form
        if form.is_valid():
            Forum.objects.create(content=form.cleaned_data['content'])
            forum = Forum.objects.all()
            response['forum'] = forum
            return redirect('/company/forum/')
        else:
            forum = Forum.objects.all()
            response['forum'] = forum
            response['form'] = form
            #return render(request, 'test.html', response)
    return redirect('/company/forum/')

def delete_forum(request, id):
    to_delete = Forum.objects.get(id=id)
    to_delete.delete()
    return redirect('/company/forum/')

app_halaman_utama/templates/halaman_utama/halaman_utama.html
{% extends "base.html" %}
{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <link href="https://fonts.googleapis.com/css?family=Spectral+SC" rel="stylesheet">
    <!-- <meta name="description" content="LAB 5"> -->
    <script type="text/javascript" src="//platform.linkedin.com/in.js">
        api_key: 81382ld8zcpgct
        onLoad: onLinkedInLoad
        authorize: true
    </script>
</head>
 
 <style>
 	body{
 		background-color: white;
 	}

    .atas{
        background-image: url(https://www.webershandwick.com/images/uploads/facebook-at-work.jpg);
        padding-bottom: 200px;
        color: black;

    }
    .kotak{
        background-color: white;
        width: 450px;
        margin: auto;
        padding-top: 50px;
        padding-right: 50px;
        padding-left: 50px;
        padding-bottom: 50px;
        align-content: center;
        border-radius: 3%;
    }

    #expert{
    transition-duration: 0.5s;
    }

    #expert:hover{
    background-color: white;
    }

    #button
    {
    height:40px; 
    width:150px; 
    margin: -50px -50px; 
    position:relative;
    top:50%; 
    left:50%;
  }

    .button
    {
        text-align: center; 
        position: relative; 
        left: 650px;    }    
 </style>

<body>
 
    
    <content>
    <div class="atas">
            <br> 
            <br>
            <br>
            <div class="kotak" id="expert" >
            <div class="container" class="profilecenter">
            <img style="display:block; margin:auto;" src="https://image.ibb.co/c3gc4b/logo.png" alt="logo" border="0" ></a>
            <br>
            <br>
            <h5 style="font-family: Spectral SC">Login to Find Your Job</h5>
            <script type="in/Login"></script>
            <div class="data">
                <div id="logout-btn">
                    
                </div>
            </div>
            </div>
            </div>
    </div>
    <div class="container-forums">
    <h1 style="padding-top: 50px; font-family: Spectral SC; size: 50px; text-align: center;">JOB VACANCY</h1>
    
    </div>
    </content>
 
    <!-- Jquery n Bootstrap Script -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>
    <script type="application/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js" integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn" crossorigin="anonymous"></script>
</body>
</html>
<script type="text/javascript">
    // companyID : 13602318 <-- Dummy Company
    // Setup an event listener to make an API call once auth is complete
    function onLinkedInLoad() {
        IN.Event.on(IN, "auth", getProfileData);
    }
 
    // Handle the successful return from the API call
    function onSuccess(data) {
        console.log(data);
        getCompanyData();
        window.location.replace("/company/profile");
        // $('#logout-btn').html('<button class="logout" onclick="logout()" style="width:10%; height:10%"> Logout </button>');

    }

    // Handle the successful return from the API call
    function displayProfileData(data){
    console.log(data);
    var user = data.values[0];
    $("#logout-btn").append('<a class="btn btn-primary btn-lg" href="/profile/" role="button">Company Dashboard &raquo;</a>')
    $("#name").append('Logged in as '+user.firstName+' '+user.lastName);
    $("#space-logout").append('<li class="nav-item"><a class="btn btn-danger" onclick="logout()">Logout</a></li>');
    document.getElementById('profileData').style.display = 'block';
}
 
    // Handle an error response from the API call
    function onError(error) {
        console.log(error);
    }
 
    // Use the API call wrapper to request the member's basic profile data
    function getProfileData() {
        IN.API.Raw("/people/~").result(onSuccess).error(onError);
 
    }

    // Remove profile data from page
    function removeProfileData(){
    document.getElementById('profileData').remove();
    window.location = "/";
    }
 
    function logout() {
        IN.User.logout(success_logout);
    }

    function success_logout(){
        $('#data').html('');
        alert("logout")
        location.reload()
    }
 
    function getCompanyData() {
        IN.API.Raw("/companies/13602318:(id,ticker,name,company-type,specialties,website-url)?format=json").result(render).error(onError);
    }
 
    function render(data) {
        console.log(data);
        $(".data").html()
    }

    // function hideReplies(id){
  //   var list = document.getElementById("reply-"+id);
  //   var button = document.getElementById("btn-show-comment-"+id);
  //   list.setAttribute("hidden", "true");
  //   button.href = "javascript:showReplies(" + id +",true)";
  //   button.innerHTML = "Show replies";
  //   }

  //   function showReplies(id, isCalled){
  //   var list = document.getElementById("reply-"+id);
  //   var button = document.getElementById("btn-show-comment-"+id);

  // if (!isCalled) {
  //   console.log("initiating ajax call");

  //   $.ajax({
  //     type:"GET",
  //     url:"/fitur4/get_comment/?id=" + id,
  //     success: function(result) {
  //       console.log("ajax call success");
  //       var reply_list = $("#reply-"+id);
  //       console.log(result.length);
  //       result.forEach(function(item, index, arr){
  //         console.log(index);
  //         var name = item['name'];
  //         var title = item['title'];
  //         var content = item['content'];
  //         console.log(name + " " + title + " " + content);
  //         text_content = '<li class="list-group-item">' +
  //           '<h5 class="card-title">' + name + '</h5>' + 
  //           '<h6 class="card-subtitle text-muted">' + title + '</h6>' + 
  //           '<p class="card-text">' + content + '</p>' + 
  //           '</li>';
  //         reply_list.append(text_content);
  //       });
  //       button.href = "javascript:hideReplies(" + id + ")";
  //       button.innerHTML = "Hide replies"
  //       list.removeAttribute("hidden");

  //     },
  //     error: function(result) {
  //       alert("error cuy");
  //     }
  //   });
  // } else {
  //   list.style.visibility = "visible";
  //   button.href = "javascript:hideReplies(" + id + ")";
  //   button.innerHTML = "Hide replies";
  //   list.removeAttribute("hidden");
  // }
  //   function hideReplies(id){
  //   var list = document.getElementById("reply-"+id);
  //   var button = document.getElementById("btn-show-comment-"+id);
  //   list.setAttribute("hidden", "true");
  //   button.href = "javascript:showReplies(" + id +",true)";
  //   button.innerHTML = "Show replies";
  //   }

  //   function showReplies(id, isCalled){
  //   var list = document.getElementById("reply-"+id);
  //   var button = document.getElementById("btn-show-comment-"+id);

  // if (!isCalled) {
  //   console.log("initiating ajax call");

  //   $.ajax({
  //     type:"GET",
  //     url:"/fitur4/get_comment/?id=" + id, YANG INI FITUR TETEH KAYANYA
  //     success: function(result) {
  //       console.log("ajax call success");
  //       var reply_list = $("#reply-"+id);
  //       console.log(result.length);
  //       result.forEach(function(item, index, arr){
  //         console.log(index);
  //         var name = item['name'];
  //         var title = item['title'];
  //         var content = item['content'];
  //         console.log(name + " " + title + " " + content);
  //         text_content = '<li class="list-group-item">' +
  //           '<h5 class="card-title">' + name + '</h5>' + 
  //           '<h6 class="card-subtitle text-muted">' + title + '</h6>' + 
  //           '<p class="card-text">' + content + '</p>' + 
  //           '</li>';
  //         reply_list.append(text_content);
  //       });
  //       button.href = "javascript:hideReplies(" + id + ")";
  //       button.innerHTML = "Hide replies"
  //       list.removeAttribute("hidden");

  //     },
  //     error: function(result) {
  //       alert("error cuy");
  //     }
  //   });
  // } else {
  //   list.style.visibility = "visible";
  //   button.href = "javascript:hideReplies(" + id + ")";
  //   button.innerHTML = "Hide replies";
  //   list.removeAttribute("hidden");
  // }


 
</script>

{% endblock %}

app_menanggapi/templates/app_menanggapi/app_menanggapi.html
{% extends "base.html" %}
{% block content %}
{% load static %}
<div class="container">
	<style>
		img {
			float:left
		}
	</style>
	<body id="forum">
	{% for data in forum reversed %}
		<img src="https://media-exp2.licdn.com/mpr/mpr/shrink_100_100/AAIAAwBqAAAAAQAAAAAAAAtBAAAAJGZmMDk1MTcyLTg3YmItNGJjNS1hMGQwLTYzMjIxYmQwYzYwZA.png" width=50px height=50px></img>
		<p id="postingan">{{data.content}}</p>
		<h5 id="tanggal">{{data.created_date}}</h5>
		<form id="form" method="POST" action="{% url 'menanggapi:tambah_tanggapan' %}">
			{% csrf_token %}
			{{ CommentForm }}
			<br>
            <button type="Post" class="btn btn-default">Post</button>
        </form>
		<hr>
	{%endfor%}
	</body>
</div>
{% endblock %}

app_profile/templates/profile.html
{% extends "base.html" %}
{% load staticfiles %}
{% load static %}
{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <!-- <meta name="description" content="LAB 5"> -->
    <meta name="author" content="{{author}}">
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet">
    <script type="text/javascript" src="//platform.linkedin.com/in.js">     
        api_key: 81382ld8zcpgct
        onLoad: onLinkedInLoad
        authorize: true
	</script>

    <title>
        Profile
    </title>

    <style>
        .data {
            width: 50%;
        }

        .profile-container {
            display: grid;
            padding: 20px;
        }

        .company-img {
            width: 120px;
            height: auto;
            margin: 10px 0px 10px 0px;
            position: 25%;
        }

    </style>
</head>


<body>
    <div class="profile-container">
        <script type="in/Login"></script> 

        <div class="data">

        </div>

        <div id="logout-btn">

        </div>
    </div>

    <!-- Jquery n Bootstrap Script -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>
    <script type="application/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js" integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn" crossorigin="anonymous"></script>
</section>
</body>
</html>
<script type="text/javascript">
    // companyID : 13602318 <-- Dummy Company
    // Setup an event listener to make an API call once auth is complete
    function onLinkedInLoad() {
        IN.Event.on(IN, "auth", getProfileData);
    }

    // Handle the successful return from the API call
    function onSuccess(data) {
        console.log(data);
        getCompanyData();
        $('#logout-btn').html('<button class="logout" onclick="logout()" style="width:10%; height:10%"> Logout </button>');
    }

    // Handle an error response from the API call
    function onError(error) {
        console.log(error);
    }

    // Use the API call wrapper to request the member's basic profile data
    function getProfileData() {
        IN.API.Raw("/people/~").result(onSuccess).error(onError);

    }

    function logout() {
        IN.User.logout(success_logout);
    }

    function success_logout() {
        window.location.replace('/halaman_utama/')
    }

    function getCompanyData() {
        IN.API.Raw("/companies/13602318:(id,ticker,name,company-type,specialties,website-url)?format=json").result(render).error(onError);
    }

    function render(data) {
        console.log(data);
        spec = "";

        for (i = 0; i < data.specialties.values.length; i++) {
            spec += "<ul> > " + data.specialties.values[i] + "</ul>"
        }

        $(".data").html(
            '<h2> Welcome to Our Company </h2>' +
            '<img class="company-img" src="https://vignette.wikia.nocookie.net/cityville/images/0/03/Empire_State_Building.png/revision/latest?cb=20110117174002">' +
            '<div class="panel panel-default">' +
                '<div class="panel-heading">' +
                    '<h2> Company Profile </h2>' +
                '</div>' +
                '<div class="panel-body">' +
                    '<p> Company Name : ' + data.name + '</p>' +
                    '<p> Company Type : ' + data.companyType.name + '</p>' +
                    '<p> Company URL : ' + data.websiteUrl + '</p>' + 
                    '<p> Secialties : ' + '</p>'+ spec +
                    '<a style="float:left; margin-right:5px;" href="#" class="btn btn-danger pull-right"> Forum </a>' +
                    '<a style="float:left; margin-right:5px;" href="#" class="btn btn-danger pull-right"> Search User </a>' +
                '</div>' +
                '<div class="panel-footer">' +
                    
                '</div>' +
            '</div>' 
        )
    }

</script>
{% endblock %}

forum_lowongan/templates/forum.html
{% extends "base.html" %}
{% block content %}
{% load staticfiles %}
{% load static %}

<title>Forum Lowongan</title>  

<script type="text/javascript" src="//platform.linkedin.com/in.js">
  api_key:   81382ld8zcpgct
  onLoad:    checkLoggedIn
  authorize: true
</script>
<link rel="stylesheet" type="text/css" href="{% static 'css/forum.css' %}" />

  <section style="display: none;">
    <!-- Main body -->
    <div class="container" style="margin-top: 60px; padding-top: 15px;">
      <div class="row">
        <h3>Forum Lowongan</h3>
      </div>
      <div class="row">
        <div class="col-sm-12">
          <div class="flex" style="margin-top: 20px">
            <div class="card-block">
              <!-- Form for new status -->
              <form class="card-text" method="POST" action="{% url 'forum_lowongan:add' %}">
                {% csrf_token %}
                <div class="card">
                  <div class="card-header" style="font-family: Spectral SC">
                    Deskripsi
                  </div>
                    <textarea class="form-control" name="content" rows="5" id="content" style="width: 100%" title="content"></textarea>
            
                </div>
              <button type="submit" class="btn btn-primary float-left" style="margin: 10px 0 25px 0" id="button"> Submit </button>
              </form>
            </div>
          </div>
          
        </div>
      </div>
    </div>
    <!-- Print errors if any -->
    {% if form.errors %}
      {% for field in form %}
          {% for error in field.errors %}
              <div class="alert alert-danger">
                  <strong>{{ error|escape }}</strong>
              </div>
          {% endfor %}
      {% endfor %}
      {% for error in form.non_field_errors %}
          <div class="alert alert-danger">
              <strong>{{ error|escape }}</strong>
          </div>
      {% endfor %}
    {% endif %}
    {% for i in forum reversed %}
      <div class="card">
        <div class="card-header" style="font-family: Spectral SC" id="lowongan">
          Lowongan
        </div>
        <div class="card-body">
          <blockquote class="blockquote mb-0">
            <p class="card-text"> {{ i.content }} </p>
            <footer class="blockquote-footer">{{ i.date }}</footer>
          </blockquote>
        </div>
      </div>
    {% endfor %}
    </div>

        <nav>
          {% if forum.has_other_pages %}
          <ul class="pagination" style="justify-content: center; margin-top: 20px">
            {% if forum.has_previous %}
              <li class="page-item"><a class="page-link" href="?page={{ forum.previous_page_number }}">&laquo;</a></li>
            {% else %}
              <li class="page-item disabled"><span class="page-link">&laquo;</span></li>
            {% endif %}
            {% for i in forum.paginator.page_range %}
              {% if forum.number == i %}
                <li class="page-item active"><span class="page-link">{{ i }} <span class="sr-only">(current)</span></span></li>
              {% else %}
                <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
              {% endif %}
            {% endfor %}
            {% if forum.has_next %}
              <li class="page-item"><a class="page-link" href="?page={{ forum.next_page_number }}">&raquo;</a></li>
            {% else %}
              <li class="page-item disabled"><span class="page-link">&raquo;</span></li>
            {% endif %}
          </ul>
          {% endif %}
        </nav>
    </section>

<script src="{% static 'js/forum.js' %}"></script>
{% endblock %}

templates/base.html
{% load staticfiles %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Ling In</title>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
	<link href="https://fonts.googleapis.com/css?family=Cookie" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css?family=Spectral+SC" rel="stylesheet">
	<link href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet">
	<link rel="shortcut icon" href="">
</head>
<style>
	body {
		/*margin:0px;*/
		background-color: white;
		background-repeat : none;
		background-size: cover;
		font-family: Spectral SC;
	}

	.data {
	    width: 50%;
	}

	.company-img {
	    width: 120px;
	    height: auto;
	    margin: 10px 0px 10px 0px;
	    position: 25%;
	}
/*	.home {
		padding: 0px 100px 0px 100px
	}

	.stats-container {
		margin-left: 50px;
		margin-right: 50px; 
		height: 100%
	}
	.topnav {
		overflow: hidden;
		background-color: #474747;
		box-shadow: 0px 0px 0px red inset;
		padding-right: 100px;
		padding-left: 100px
	}

	.topnav a {
		display: block;
		float: right;
		color: white;
		text-align: center;
		font-size: 15px;
		padding: 10px 15px;
		text-decoration: none;
		border-left: 1px #686868 solid;
		border-right: 1px #686868 solid;
		transition : box-shadow 0.2s;
	}

	.topnav p {
		display: block;
		float: left;
		padding: 0px;
	}
	.profile-item{
		margin-left: 20px
	}

	.topnav a:hover {
		box-shadow: 0px -4px 0px red inset;		
	}

	.topnav a.first-item {
		border-right: 2px #686868 solid;
	}

	.topnav a.last-item {
		border-left: 2px solid #686868;
	}*/
</style>
<body style="background-image: = #d299c2; background-size: cover; background-repeat : none;">
	<div class="container-fullwidth">
        <nav class="navbar navbar-default navbar-expand-lg navbar-light bg-light">
          <a class="navbar-brand" href="/halaman_utama/" style="font-family: Cookie; font-size: 25px ">Ling In</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
              <ul class="nav navbar-nav">
        		<li><a href="{% url 'profile:index' %}">Profile</a></li>
        		<li><a href="{% url 'forum_lowongan:index' %}">Forum</a> </li>
        		<li><a href="{% url 'menanggapi:index' %}">Reply</a> </li>
      		</ul>
            </ul>
          </div>
        </nav>
    </div>

	{% block content %}
	{% endblock %}	
</body>
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script type="application/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.4/js/select2.min.js"></script>
<script src="https://code.jquery.com/qunit/qunit-2.4.1.js"></script>
</html>